// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhEPcxAbUkVcrmKB2yurj_J0nkY33UUbc',
    appId: '1:256599367266:web:6934a3ca6bef73e78efb3b',
    messagingSenderId: '256599367266',
    projectId: 'ecowico-4c229',
    authDomain: 'ecowico-4c229.firebaseapp.com',
    databaseURL: 'https://ecowico-4c229-default-rtdb.firebaseio.com',
    storageBucket: 'ecowico-4c229.firebasestorage.app',
    measurementId: 'G-YVENK7VMD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9iJJSW45WGjb0kC_Q5hHFkt7E6XgjR8w',
    appId: '1:256599367266:android:c33eec6ec54a60df8efb3b',
    messagingSenderId: '256599367266',
    projectId: 'ecowico-4c229',
    databaseURL: 'https://ecowico-4c229-default-rtdb.firebaseio.com',
    storageBucket: 'ecowico-4c229.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ybuNDMx7hte8WG2i6YduSPH4-x6NPAw',
    appId: '1:256599367266:ios:b8430ae8a908f3068efb3b',
    messagingSenderId: '256599367266',
    projectId: 'ecowico-4c229',
    databaseURL: 'https://ecowico-4c229-default-rtdb.firebaseio.com',
    storageBucket: 'ecowico-4c229.firebasestorage.app',
    iosClientId: '256599367266-f33gviga63g550g1kt58pm8laiqk6lql.apps.googleusercontent.com',
    iosBundleId: 'com.example.notif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5ybuNDMx7hte8WG2i6YduSPH4-x6NPAw',
    appId: '1:256599367266:ios:b8430ae8a908f3068efb3b',
    messagingSenderId: '256599367266',
    projectId: 'ecowico-4c229',
    databaseURL: 'https://ecowico-4c229-default-rtdb.firebaseio.com',
    storageBucket: 'ecowico-4c229.firebasestorage.app',
    iosClientId: '256599367266-f33gviga63g550g1kt58pm8laiqk6lql.apps.googleusercontent.com',
    iosBundleId: 'com.example.notif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhEPcxAbUkVcrmKB2yurj_J0nkY33UUbc',
    appId: '1:256599367266:web:e1e3d0da30e784628efb3b',
    messagingSenderId: '256599367266',
    projectId: 'ecowico-4c229',
    authDomain: 'ecowico-4c229.firebaseapp.com',
    databaseURL: 'https://ecowico-4c229-default-rtdb.firebaseio.com',
    storageBucket: 'ecowico-4c229.firebasestorage.app',
    measurementId: 'G-2M3ELN7SNW',
  );

}